### ISSUE TITLE
Dynamic fragments and the unique fragments warning

### ISSUE THREAD

**Issue by SachaG** [apollographql/graphql-tag#100]
in Vulcan, I added a system that lets you [extend fragments](http://docs.vulcanjs.org/fragments.html). For example, you could imagine that a PostsThumbnail package would extend the `PostItem` fragment with a `thumbnail` field. 

The problem with these "dynamic" fragments is that they might sometimes be generated twice: once as the normal version, and then once more as the "extended" version, which leads to the ` fragment with name PostItem already exists.` warning. 

I've done my best to avoid these situations and only declare each fragment once, but I still have a few cases where I just haven't been able to ensure the fragment generation code only runs once. 

So my questions are:

1) Is that warning really necessary? Or alternatively, could there be a way of turning it off?
2) If not, is there a way to "unregister" a fragment from whatever is keeping track of them to ensure uniqueness (so that it can be declared again without the warning)?

**Comment by jnwng** [comment]
@SachaG 

1) you can use the [disableFragmentWarnings](https://github.com/apollographql/graphql-tag/blob/78ed906936feabdfb7c8fa52fad6375d77852a04/src/index.js#L177) export from `graphql-tag` to silence the fragment warnings. it was listed in the [CHANGELOG](https://github.com/apollographql/graphql-tag/blob/115136560f6b86779360190314790756734dc72a/CHANGELOG.md#v110) but isn't documented in the README, definitely would accept a PR to add it there too. hopefully this resolves 2), too.

**Comment by SachaG** [comment]
Awesome, thanks!
