### ISSUE TITLE
"process is not defined" in upgrade from 2.3.0 to 2.4.0

### ISSUE THREAD

**Issue by crumhorn** [apollographql/graphql-tag#106]
From 2.3.0 to 2.4.0 there seems to be breaking changes somehow in conjunction with the latest GraphQL versions. The following dependencies works fine (in an Angular2 environment, also latest versions):

    "graphql": "0.10.3",
    "graphql-anywhere": "3.1.0",
    "graphql-relay": "0.5.2",
    "graphql-tag": "2.3.0",
    "graphql-tools": "1.0.0",

but with version 2.4.0 of graphql-tag, the following stacktrace is produced:

zone.js:391 Error: process is not defined
  Evaluating http://localhost:3000/node_modules/graphql/utilities/assertValidName.js
  Evaluating http://localhost:3000/node_modules/graphql/type/definition.js
  Evaluating http://localhost:3000/node_modules/graphql/utilities/valueFromAST.js
  Evaluating http://localhost:3000/node_modules/graphql/utilities/buildASTSchema.js
  Evaluating http://localhost:3000/node_modules/graphql-tag/src/index.js
  Evaluating http://localhost:3000/app/core/services/HttpService.js
  ...

Are there some breaking changes that I missed somewhere?

**Comment by jnwng** [comment]
Likely an issue with the descriptors: https://github.com/apollographql/graphql-tag/pull/99/files

Will investigate and confirm.

**Comment by jnwng** [comment]
Use 2.3 for now.

**Comment by crumhorn** [comment]
Just updated to 2.4.2 and I don't see this issue any more :+1:

**Comment by jnwng** [comment]
closing in favor of #107
