### ISSUE TITLE
Loader failed to compile

### ISSUE THREAD

**Issue by HBCharles** [apollographql/graphql-tag#118]
I tried to use the graphql tag loader to export my graphql script, but i'm having the following error : 

![image](https://user-images.githubusercontent.com/9991267/29110355-b225c642-7ce6-11e7-9d34-feb2d1b49bdb.png)

I've just added the following lines in my webpack.config.dev : 

![image](https://user-images.githubusercontent.com/9991267/29110536-3b4cc5ce-7ce7-11e7-81c8-eaf38fcd71d9.png)

Both graphql and graphql-tag are installed in my packages.json 

![image](https://user-images.githubusercontent.com/9991267/29110581-62c644fe-7ce7-11e7-8b91-7942b6b050fe.png)

**Comment by AlexanderChen1989** [comment]
same problem

**Comment by AlexanderChen1989** [comment]
@HBCharles your problem solved?

**Comment by jnwng** [comment]
@HBCharles do you mind sharing the rest of your webpack config? based on the output there, it doesn't look like `graphql-tag/loader` is actually running on your graphql file; it looks like another load is consuming it.

**Comment by jnwng** [comment]
closing for now, as i think this is likely a webpack loader issue
