### ISSUE TITLE
Testing GraphQL backend using tagged queries and mutations

### ISSUE THREAD

**Issue by CrocoDillon** [apollographql/graphql-tag#120]
Hello, I'm using `react-apollo` in some of my projects. Currently I'm placing fragments, queries and mutations in their own JS files so I can use them to test the backend (including stuff like permissions, so I can't use the mock provider).

Except I'm not sure what the best approach here is.

Those files look a little bit like:

```js
// user/graphql/queries.js
import { gql } from 'react-apollo'
export const userQuery = gql`...`
```

Should I use the vanilla JS version of Apollo ([like so](https://github.com/apollographql/apollo-client#usage)) to send the query to the backend or is there any smarter way to do so?

**Comment by jnwng** [comment]
@CrocoDillon  just to clarify, `graphql-tag` is only responsible for parsing GraphQL documents (normally for use within a client like `apollo-client` or `relay`). 

if you want to build an integration test that verifies the entire flow of submitting a GraphQL server to your backend of choice, you can actually just POST a request to your backend `/graphql` endpoint — `apollo-client` is just doing that under the hood and intelligently modifying the client-side cache, nothing more. 

here's a good example of what those tests [might look like](https://github.com/apollographql/apollo-server/blob/ef3ead734be3cb74a82d85f98e27b271a2ca3382/packages/apollo-server-integration-testsuite/src/index.ts#L153-L161), taken from the `apollo-server` test suites.

hope that helps!

**Comment by CrocoDillon** [comment]
Thanks! Will look into those examples.

I actually thought about just sending a query string using a simple POST request but since I already have the queries (in `gql` format) I want to use that to avoid repetition.

**Comment by jnwng** [comment]
Ah I see, that makes sense. You should be able to call JSON.stringify on
the queries wrapped in `gql` to return them back to a string which you can
use in your POST request.

**Comment by CrocoDillon** [comment]
Awesome, will try that. Thanks a lot 😄

**Comment by BjoernRave** [comment]
@CrocoDillon I know this is already some time ago, but I am in the same situation where I would like to reuse my gql queries, the problem for me is passing in variables, did you find a way to do that?

**Comment by CrocoDillon** [comment]
@BjoernRave I don't even remember what I did eventually. Now with hooks everything is a little bit different anyway, so I'd probably just create a component that uses the Apollo hooks to test without using mock data.
