### ISSUE TITLE
Enable webpack loader to preprocess to string

### ISSUE THREAD

**Issue by gpoitch** [apollographql/graphql-tag#121]
First, thanks for this awesome tool, it's working great!

I am using the webpack loader and pre-processing my static .graphql files to the AST.
It'd be nice for an option on the loader to use `graphql/language/printer` to serialize the AST to a string.  The AST + printer is overhead in my bundle and I just want the compiled strings so I can send off fetch requests with them.

I can submit a PR if you think this is valuable.

**Comment by jnwng** [comment]
@gpoitch yea, i think that's a good suggestion to avoid having to send `graphql-js` to the client. here's a couple of babel plugins that do this already: https://github.com/apollographql/graphql-tag#babel-preprocessing 

happy to discuss exposing that same functionality here in `graphql-tag/loader` if that still is useful for you outside of the babel plugins!

closing this for now. please re-open if this is important!
