### ISSUE TITLE
graphql-tag/loader "Critical dependency: the request of a dependency is an expression"

### ISSUE THREAD

**Issue by medv** [apollographql/graphql-tag#127]
Latest webpack, latest graphql-tag, following the readme instructions.

```
WARNING in ./src/api/Community/queries/communities.graphql
Critical dependency: the request of a dependency is an expression
```

communities.graphql:
```
#import core from '../fragments/core.graphql'

query getCommunities($type: CommunityType) {
  communities(type: $type) {
    ...core
  }
}
```

core.graphql
```
fragment core on Community {
  id
  name
}

```

Compilation is successful, but this webpack warning comes up once for every import of a fragment.

**Comment by rasdaniil** [comment]
Just struggled myself (because it's not mentioned in README)..
should be just
`#import core from '../fragments/core.graphql'`

**Comment by jnwng** [comment]
glad you figured it out @rasdaniil. would happily accept a PR clarifying the docs to make sure others dont hit this same issue!
