### ISSUE TITLE
Argument has invalid value error

### ISSUE THREAD

**Issue by heaks** [apollographql/graphql-tag#129]
Can't provide hardcoded property string, it doesn't work with query like this one
we have a query
```
const carsQuery = gql`
  query(
    $status: CarStatuses,
  ) {
    cars(
      color: "red"
      status: $status,
      limit: 20,
    ) {
      _id
      type
    }
  }
`;
```
and schema
```
type Query {
  cars(
    status: CarStatuses
    limit: Int
    color: CarColors
  ): [Cars]
```

```
enum CarColors {
   red
   blue
   white
}
```
I get error: Argument "color" has invalid value "red"
works only if we pass this as variable (pretty much the same stuff):
```
const carsQuery = gql`
  query(
    $status: CarStatuses,
    $color: CarColors,
  ) {
    cars(
      color: $color
      status: $status,
      limit: 20,
    ) {
      _id
      type
    }
  }
`;
```
+
```
graphql(carsQuery, {
    props: () => {},
    options: () => ({
      variables: { status:'ok', color: 'red'},
    }),
  });
```
Why is this happening ?

**Comment by jnwng** [comment]
hello @heaks!

enums aren't represented as strings in the query document — in this case, your query should look like
```graphql
const carsQuery = gql`
  query(
    $status: CarStatuses,
  ) {
    cars(
      color: red # Note that this isn't quoted!
      status: $status,
      limit: 20,
    ) {
      _id
      type
    }
  }
`;
```

see working example here: https://launchpad.graphql.com/4rz59lv4w9

for future reference, `graphql-tag` is just a thin wrapper on [graphql-js](https://github.com/graphql/graphql-js) itself, and i think this would be better to ask on StackOverflow or perhaps on one of the many [graphql community forums](http://graphql.org/community/)

apologies for taking so long to get back to you!
