### ISSUE TITLE
[Feat] Allow to create built in types

### ISSUE THREAD

**Issue by luchillo17** [apollographql/graphql-tag#130]
An exmple of this is `JSON`, for example i have a column in my db that is an interval, so i get back an object like this:
```ts
entity.duration = {
  seconds: 5,
  minutes: 15,
  ...
}
```
And it contains the interval time split in `seconds`, `minutes`, `hours`, `days`, `months` & `years`, some of them come, some don't depending on how big the interval is to fit in those categories.

I don't want to define a type for it nor query for each field, i want to give back the object as it comes from the DB to the client.

Currently i'm forced to `JSON.stringify()` the object & then parse it on client side, it would be great if either JSON is added or a way to add builtin types is documented for this lib.

**Comment by jnwng** [comment]
@luchillo17 `graphql-tag` is just a thin wrapper over [graphql-js](https://github.com/graphql/graphql-js), i think you would be better served looking for more information there

please re-open if you think this is indeed something that `graphql-tag` should be handling.

**Comment by luchillo17** [comment]
The thing is there exists custom types like https://github.com/taion/graphql-type-json, but i can't find a way to add such types to the graphql query language so that graphql-tag can use it in a `.gql` file.

**Comment by jnwng** [comment]
check out the tests
<https://github.com/taion/graphql-type-json/blob/master/test/index.js#L40-L43>
which
show how its used when using graphql-js to create schemas. once its in the
schema, you can use it in `graphql-tag`
