### ISSUE TITLE
2.6.0 (PR #122) Multi Query Import Isn't Working With TypeScript?

### ISSUE THREAD

**Issue by spentak** [apollographql/graphql-tag#133]
Using TypeScript
The old way that works (but only allows one query per file):

`const query = require('../graphql/slope.graphql');`
`const slopesQL = graphql<Props, {}>(query);`

The new ways per 2.6.0:

`const Queries = require('../graphql/slope.graphql');`
`const slopesQL = graphql<Props, {}>(Queries.GetSlopes);`

Throws runtime err:

```bash
Argument of undefined passed to parser was not a valid GraphQL DocumentNode. You may need to use 'graphql-tag' or another method to convert your operation into a document
```

Finally this method cannot even resolve the file:

`import { GetSlopes, Slope } from '../graphql/slope.graphql';`

The query file slope.graphql:

```
fragment basicSlopeData on Slope {
    name
    orderNumber
}

query GetSlopes {
    slopes {
        ...basicSlopeData
        skillTracks {
            name
            orderNumber
        }
    }
}

query Slope($id: String) {
    slope(id: $id) {
        ...basicSlopeData
    }
}
```

**Comment by jnwng** [comment]
interesting. @spentak is there a stack that goes along with that error? i just want to confirm that this is indeed a typescript issue or if for some reason there was a regression in webpack.

**Comment by jnwng** [comment]
closing this for now. @spentak let me know if this still an issue.

**Comment by daggerjames** [comment]
It is still existing on my Code.

For example, graphql-tag would parse multiple queries in same graphql as 
``` 
QueriesGraphql
{
  Query1 : {kind: "Document", definitions: ...}
  Query2: {kind: "Document", definitions: ...}
  kind: "Document"
}
```

However, typescript would check QueriesGraphql as {kind, loc, definitions} without properties named 'Query1' or 'Query2', in turn we could not access Query1 / Query2 directly.

A working around would use 'any' like: 
```
(QueriesGeraphql as any).Query1
```
