### ISSUE TITLE
Update peer graphql version to allow ^0.12.0

### ISSUE THREAD

**Issue by pSchaub** [apollographql/graphql-tag#134]
> npm WARN graphql-tag@2.6.0 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 but none is installed. You must install peer dependencies yourself.

But I have installed GraphQL 0.12.3

See: https://github.com/apollographql/graphql-tag/blob/master/package.json#L33

**Comment by stubailo** [comment]
Yep, that just came out a day ago, we will update very soon! The package should still work just fine though :]

**Comment by stubailo** [comment]
If you want, feel free to open a PR :] it's a small one but still could be fun

**Comment by jnwng** [comment]
fixed in `2.6.1`. enjoy!
