### ISSUE TITLE
README claims that this package does "printing" but never mentions it again

### ISSUE THREAD

**Issue by glasser** [apollographql/graphql-tag#139]
The README says this package does "GraphQL printing and parsing with bundled dependencies". But I don't see anything else in the README about printing, just parsing, and a super cursory look at the `src` directory doesn't show me anything else printing-related. Is that line inaccurate, or is something missing from the docs?

**Comment by jnwng** [comment]
@glasser in the past we used to bundle `graphql-js` into this library and exposed (by proxy) the `print` and `parse` functions that `graphql-js` exposes. as of the latest major version that pushed `graphql-js` to peerDependencies, that is no longer true, so the docs are inaccurate.

happy to accept a PR to better represent when `graphql-tag` is doing now

**Comment by glasser** [comment]
Thanks, I did!
