### ISSUE TITLE
Could .toString return the graphql string back?

### ISSUE THREAD

**Issue by caub** [apollographql/graphql-tag#144]
So we could use this as a formatting tool as well

**Comment by jonaskello** [comment]
I also want the original string back becuase I need to prefix with `gql` to make code generation work, but then I also want to use the original string when building dynamic queries.

**Comment by jonaskello** [comment]
I found that you can get the string from the resulting gql document like this:

```typescript
const myFragment = gql` .....some GQL... `;

console.log(getGqlString(myFragment));

function getGqlString(doc: DocumentNode) {
  return doc.loc && doc.loc.source.body;
}
```

**Comment by caub** [comment]
@jonaskello yes, but it just return the original string, not formatted, so not interesting

**Comment by jonaskello** [comment]
@caub Yes that is true, for my case it was enough, but for formatting it is not useful.

**Comment by caub** [comment]
@develomark thanks! perfect https://runkit.com/caub/5a6b7290a42f2100123f9689

Ideally there would be an option to have the pretty query like that or a minimal one (more for http requests) (or maybe it doesn't matter much to save a few chars there)

Closing, thanks again

**Comment by jnwng** [comment]
Thank you! This is what we’re using under the hood in this library anyway

**Comment by jnwng** [comment]
We previously proxied that function and removed it in lieu of using the
graphql-js library directly (mostly because we moved graphql-js to a
peerDependency). I think documentation would be a good solution here, what
do you think?

**Comment by develomark** [comment]
Feels really logical to me to do:
```
import query from "./query.gql"
query.print()
```
Now that we have imports inside `graphql` files, it isn't immediately obvious what's being constructed. One less step has got to be useful.

**Comment by jnwng** [comment]
I see, that’s a good point. Let me sit on it a little and revisit why we
removed the proxy in the past, but this use case seems pretty
straightforward.

**Comment by develomark** [comment]
Actually, an additional benefit would be to be able to import `gql` files and use them as AST documents or strings.

i.e.
```
import query from "./query.gql"
const composedQuery = `${query} ...More stuff`
```

**Comment by jnwng** [comment]
We already do support interpolation, that’s how fragments are interpolated
into queries.

**Comment by conatus** [comment]
It would be awesome is `toString()` was supported. I guessed this method would be there, was surprised it wasn't then ended up on this issue - which is great - but it would be better if it was in the mix by default.

**Comment by robbyemmert** [comment]
Right now my network request payloads are huge because it's sending the whole AST object. This also makes it much harder to debug network requests. A .toJSON function would solve this problem, because it would automatically convert to a string when serialized into JSON (i.e. sent over the network) just like Dates are serialized automatically.

**Comment by robbyemmert** [comment]
In my case, there's no point in parsing the AST on the client only to serialize it to string... It would be great if I can avoid parsing it in the first place.

**Comment by Vadorequest** [comment]
When I try to print my query using `console.log('builtQuery', print(builtQuery));` I get 

>Invalid AST Node: { query: { kind: "Document", definitions: [Array] }, variables: { skip: 0, first: 10, orderBy: "id_ASC", where: {} }, parseResponse: [function] }

Eventually figured out I had to do `console.debug('builtQuery', print(builtQuery.query));` and it worked perfectly.

**Comment by jeliasson** [comment]
Any update on this? Having `.toString()` would be really helpful. 😊

**Comment by dnknitro** [comment]
You can get formatted query by using print function:
```Javascript
import { print } from 'graphql';

const query = gql`
  query ...
`;

console.log(print(query));
```

**Comment by balazsorban44** [comment]
https://github.com/nhi/graphql-operations-string-loader Created a webpack loader that reads graphql files (even with multiple operations per file) and exports them as named exports in a string format

**Comment by novellizator** [comment]
So guys what do we do if there are imports in the query? How are they resolved?

**Comment by torressam333** [comment]
> @caub you can use `graphql/language/printer`
> 
> So based upon @jonaskello's slug:
> 
> ```
> import { print } from 'graphql/language/printer'
> 
> console.log(print(query)) 
> ```
> 
> This will return the full string including any fragments etc.

If you need the docs: https://graphql.org/graphql-js/language/#print

**Comment by jazanne** [comment]
having this as a toString method would be clutch
