### ISSUE TITLE
Strange problem with importing

### ISSUE THREAD

**Issue by TheDeveloperTom** [apollographql/graphql-tag#153]
1. ![image](https://user-images.githubusercontent.com/25426552/35993684-c9191104-0d16-11e8-851e-ed852a9b2b79.png)

2. 
![image](https://user-images.githubusercontent.com/25426552/35993840-3e89dfb8-0d17-11e8-8e7c-480ab6b6d627.png)

3. 
![image](https://user-images.githubusercontent.com/25426552/35993898-76be75a6-0d17-11e8-9ae9-4b4d9d5d356e.png)

But, the most interesting:
This way will work fine
![image](https://user-images.githubusercontent.com/25426552/35993777-093112e6-0d17-11e8-95c2-d6b527410f0f.png)

Thanks for the help in advance!

**Comment by zackify** [comment]
From Slack: readQuery takes a key called `query` you were passing `isAuthQuery: isAuthQuery`. Glad you figured it out :)

**Comment by TheDeveloperTom** [comment]
Thank you!
