### ISSUE TITLE
v2.7.0 breaks IE11 support

### ISSUE THREAD

**Issue by nick-penaranda-ck** [apollographql/graphql-tag#158]
#### Overview

We use `graphql-tag/loader` to load `.gql` files in a single-page application built by webpack.  That package specifies a dependency for `graphql-tag@^2.2.2`.  `graphql-tag/loader`'s output, starting with `v2.7.0`, uses `Object.assign` and `Array.prototype.find`:

https://github.com/apollographql/graphql-tag/blob/741fe33ab1b0eaa591e4adce9ea4a6e3857efe22/loader.js#L118
https://github.com/apollographql/graphql-tag/blob/741fe33ab1b0eaa591e4adce9ea4a6e3857efe22/loader.js#L111

These methods are unsupported in Internet Explorer and unexpectedly broke compatibility with that browser.  Such compatibility-breaking changes should be gated with a major revision.

We have since worked around this issue, but reporting the issue for posterity.

Thanks for looking! 🎉

#### Intended outcome

Use `graphql-tag/loader` to load `.gql` files in a way that retains the same set of supported browsers within the same major revision.

#### Actual outcome

Support for IE11 (and likely other browsers) was unexpectedly broken with the release of `v2.7.0`.  Packages with caret-scoped dependencies (e.g., `graphql-tag@^2.2.2`) automatically picked up this breaking change.

#### How to reproduce the issue

Minimally reproducible with:

index.js:
```
console.log(require('./query.gql'))
```

query.gql:
```
query { someField }
```

webpack.config.js:
```
module.exports = {
    context: __dirname,
    entry: "./index",
    output: { filename: "bundle.js" },
    module: {
        loaders: [
            {
                test: /\.gql$/,
                loader: 'graphql-tag/loader',
            }
        ]
    }
}
```

1. Build with webpack and observe `bundle.js` contains `Object.assign`, `Array.prototype.find`

**Comment by shiruken1** [comment]
Facing the same issue here. What was your workaround like? Thanks!

**Comment by vitorbal** [comment]
`Object.assign` is gone in v2.7.1. I just opened a PR to get rid of the `Array.prototype.find` usage: https://github.com/apollographql/graphql-tag/pull/176
