### ISSUE TITLE
Importing multiple queries and mutations defined as type

### ISSUE THREAD

**Issue by indegser** [apollographql/graphql-tag#160]
Hi.
Thank you for great project!

While I was developing React + ApolloClient project 
I encountered a problem.

I am using graphql-tag/loader inside my webpack to import .gql files in javascript files.
This is part of my schema.graphql

```graphql
type Query {
  book(id: ID!): Book
  books: [Book]
}

type Mutation {
  newBook(input: BookInput!): Book
  deleteBook(bookId: ID!): Boolean
  editBody(input: EditInput): Boolean
  newWebpage(input: WebpageInput!): Webpage
}
```

When i try to import this file in React project.
It seems like I can not use it like this.

```javascript
import api from 'api/schema.graphql'
...
export default graphql(api.book)(Component)
```

Is there any ways i can reference single query/mutation inside a single graphql file defined as type?

**Comment by jnwng** [comment]
@indegser its important to make the distinction between GraphQL queries and the schema. in this case, you're trying to reference a part of the schema (which defines _what_ is available), but you want to define a query (which is what you _actually_ want to retrieve)

e.g., your query is going to look like
```graphql
query {
  book(id: "fooid") { ... }
}
```

which is what your client is going to define. so i dont think you want to import from the schema like this, you want to define a new query!

i'm going to close this for now, please re-open if this wasn't clear.
