### ISSUE TITLE
Where to define object types?

### ISSUE THREAD

**Issue by moltma** [apollographql/graphql-tag#163]
Using graphql-tag in an Angular (MEAN stack) app. I have the following, from an example application (mean.io):

```
import gql from 'graphql-tag';
export const GetPostsQuery = gql`
  query Posts {
    posts {
        id
        seqnum
        name
    }
  }
`;
```

Where is the "Posts" object type defined? I can't seem to adjust the query for my own Mongo data, because I don't know where to change the Posts object definition. I'm assuming the type definition looks something like this, from http://graphql.org/learn/schema/:

```
type Character {
  name: String!
  appearsIn: [Episode]!
}
```

But where do I define the type(s)?

**Comment by jnwng** [comment]
the `Posts` here is the name of the operation, not the name of the type. the field `posts` would return `[Post]` but all of the schema definitions are on the backend in the server, not in the client.

when you're using `graphql-tag` on the client you won't be able to change the underlying schema of the server.
