### ISSUE TITLE
Imported Queries `graphql` Issue

### ISSUE THREAD

**Issue by dcflow** [apollographql/graphql-tag#166]
Hello,

There is an issue happening with imported queries inside `graphql`.
When you define the query inside the file and use it with `graphql` it works fine:
```
const AMUTATION = gql`mutation ...`
export default graphql(AMUTATION)(Component)
```
When you import it from another file you get an error:
```
import { AMUTATION } from 'file.js'
export default graphql(AMUTATION)(Component)
```
```
Argument of undefined passed to parser was not a valid GraphQL DocumentNode. 
You may need to use 'graphql-tag' or another method to convert your operation into a document. 
`...\node_modules\invariant\invariant.js:40 `
```
The `file.js` is:
```
class OtherComponent { ... }
export const AMUTATION = gql`mutation ...`
export default OtherComponent
```
The imported query object is the same as the one created inside the file.

Thank You!

**Comment by jnwng** [comment]
What does the “file” in the second example look like?

**Comment by dcflow** [comment]
The file.js is:
```
class OtherComponent { ... }
export const AMUTATION = gql`mutation ...`
export default OtherComponent
```

**Comment by jnwng** [comment]
Can you check what AMUTATION is? Is the import itself undefined?

**Comment by dcflow** [comment]
I checked it inside `componentWillMount` and it's identical if I had created inside the component.

**Comment by dcflow** [comment]
I think you are right, inside the `graphql` it is probably undefined but why?  (something to do with how `export` and `import` work)

**Comment by hopewise** [comment]
@ dcflow have you solved this issue?

**Comment by dcflow** [comment]
No @hopewise I ended up moving all the queries into a separate file

**Comment by hopewise** [comment]
Can you please show me how did you do it? as I am struggling to do like you did, as here: https://stackoverflow.com/questions/50450109/why-i-get-argument-of-undefined-passed-to-parser-was-not-a-valid-graphql-documen/50454705?noredirect=1#comment87946325_50454705

**Comment by oussamajabnouni** [comment]
Just delete the query word

Before

```
const getStudents= gql`
  query getStudents($schoolID: Int){
    allStudents(schoolId: $schoolID){
     pickUpLat
     pickUpLng
  }
}`
```
After

```
const getStudents= gql`
  getStudents($schoolID: Int){
    allStudents(schoolId: $schoolID){
     pickUpLat
     pickUpLng
  }
}`
```

**Comment by human-a** [comment]
@hopewise I ended up using fragments, for some reason if a file contains long queries and I use them more than once, one the exports will be set to ```undefined```, fragments helped solve the issue.

**Comment by thril** [comment]
@human-a I have run into the `undefined` issue before when I had a circular reference in my code - file A was importing something from file B and file B was importing something from file A. In my case, it was fragments separately defined in each. I solved this by moving them to a common "fragments" file.

**Comment by human-a** [comment]
That is a good point. Will check my code for circular references. Thanks.
