### ISSUE TITLE
[PR proposal] Make use of `graphql/utilities/separateOperations` in loader?

### ISSUE THREAD

**Issue by detrohutt** [apollographql/graphql-tag#173]
Hey @jnwng 

I've never written a webpack loader so I'm not really clear on the limitations/best practices, but I've modified most of the code from your loader for use in [`babel-plugin-inline-import-graphql-ast`](https://github.com/detrohutt/babel-plugin-inline-import-graphql-ast`).

Initially, I did the same with the code for supporting multiple operations. However, while I was refactoring my plugin yesterday, I came across the [`separateOperations`](https://github.com/graphql/graphql-js/blob/master/src/utilities/separateOperations.js) function included with `graphql`.

Using that, I was able to turn a ~100 LOC file (mostly modified code from your loader) into this:
```typescript
const createDocPerOp = (doc: any): Record<string, DocumentNode> => {
  const docMap = separateOperations(doc);
  // Set the first/only export as the default export
  return {...docMap, default: docMap[Object.keys(docMap)[0]]}
}
```

Is there any inherent reason why you couldn't leverage this function in the loader as well? There don't appear to have been any breaking changes in `separateOperations` since at least `v0.9.0` so it wouldn't be a breaking change for `graphql-tag`. If you think it's possible, I'll start on a PR to migrate `loader.js` to `separateOperations`.

**Comment by jnwng** [comment]
this looks like a good idea, but im not 100% the impact of stripping the `loc` field from the AST. this might be okay if we're doing this step last before exporting, but i have to read the code a little more thoroughly.

(if the tests pass with this change, then i dont see the harm)

**Comment by detrohutt** [comment]
I'm closing this since I've opened the pull request.
