### ISSUE TITLE
Syntax Error: Expected Name, found $

### ISSUE THREAD

**Issue by timbergus** [apollographql/graphql-tag#180]
I have the following code:

```javascript
import gql from 'graphql-tag';

export const USER_QUERY = gql `{
    query User($id: ID!) {
        getUser(id: id) {
            name
            surname
        }
    }
}`;
```

Here is the connection point:

```javascript
export default graphql(USER_QUERY, {
    name: 'User',
    options: ({ id }) => ({
        variables: { id }
    }),
})(User);
```

And the error in the title.

I am not sure if this error goes here, but I have been searching the web for this problem, and I cannot find anything. All the answers say that my code is OK, but I cannot make it work. Could you please halp me? Thanks.

**Comment by jnwng** [comment]
Apologies for brevity, I’m on my phone.

When using variables for arguments in GraphQL they must be prefixed with an
“$”. In this case, the variable you’re passing to the getUser field (“id”)
should reference the $id variable declared at the query level.

getUser(id: $id)

**Comment by jnwng** [comment]
http://graphql.org/learn/queries/#variables for reference, particularly
replacing variables in the static query

**Comment by timbergus** [comment]
I’m pretty sorry about that. That is a typo. I get the same error with the right code. I have tested it using GraphiQL and it worked. The error is in the first line `query User($id: ID!)`. If I remove the $, it throws the same error in the !, and if I remove the !, it works, but the app fails because there is no `getUser` result in the props. However, I will double check this as soon as I get a computer.

**Comment by timbergus** [comment]
Doublechecked. With this code still failing:

```javascript
import gql from 'graphql-tag';

export const USER_QUERY = gql `{
    query User($id: ID!) {
        getUser(id: $id) {
            name
            surname
        }
    }
}`;
```

The browser shows me this query in the error, and the same error as before:

```javascript
body: "{↵    query User($id: ID!) {↵        getUser(id: $id) {↵            name↵            surname↵        }↵    }↵}"
```

Seems to be OK. Could be `graphql`the one having the problem using it?

**Comment by detrohutt** [comment]
@timbergus Make sure you are using the same type for `id` in your backend schema typedefs. It seems like maybe you have it defined as type `ID` in one place and `ID!` in the other?

**Comment by timbergus** [comment]
OK. I got it. The problem is that I'm passing extra curly braces. I have test this code, and it works perfectly:

```javascript
import gql from 'graphql-tag';

export const USER_QUERY = gql `query User($id: ID!) {
    getUser(id: $id) {
        name
        surname
    }
}`;
```

I have discovered it using the importer of webpack and a code highligther for GraphQL. When creating the .graphql files, the sintax was highligted different with the curly braces and without them, so I tried.

The library is perfect. Thank you very much for your work, and sorry for the inconveniences.

Regards.

**Comment by VinaySharmaQss** [comment]
Great, I also made the same mistake. it helped.

**Comment by vinayvatsa007** [comment]
i also made the same mistake, it helped Thanks for sharing.

**Comment by Tsudhishnair** [comment]
I also made the same sort of mistake thanks for helping.

**Comment by MrSunshyne** [comment]
@detrohutt I'm using gql statements with template literals as such : 

```
return gql` query {
      ${entityTypes} {
        id
      }
    }`;
```
I get the error "Expected Name.... "

Any suggestions on how to deal with the above? 

Thanks !

**Comment by detrohutt** [comment]
@MrSunshyne it looks like you're trying to use string interpolation syntax `${}` in your query. I don't believe that is supported by the `gql` template function. You'll probably need to hard-code your field name. Hope that helps, good luck!

**Comment by MrSunshyne** [comment]
@detrohutt That's correct. I'm using native javascript string interpolation. 
I'm not sure what you mean by "it's not supported", as it definitely works. 

I'm having issues with the syntax highlighting.

> You'll probably need to hard-code your field name
That's not an option because my application only knows the name of the mutation at runtime. 

Here's another working example :

![Screenshot 2019-07-29 at 17 58 11](https://user-images.githubusercontent.com/1721611/62054364-7acaea80-b22a-11e9-98fc-c9fed5845b52.png)

The above would translate to `article_delete` in this case, which works fine. I can also have `author_delete` or `whatever_delete`. 
I have no idea if gql statements was built to be used this way, but so far this is the only way I found to create my queries at runtime. Apologies if there's something I missed. This is my first graphql project. 

Any other hints? Much appreciated

**Comment by JulesMike** [comment]
> it looks like you're trying to use string interpolation syntax ${} in your query

I do confirm that using `interpolation syntax ${}` in a query works just fine but the syntax highlighting is all other the place like @MrSunshyne showed and described.

**Comment by digeomel** [comment]
Same here. String interpolation in GraphQL queries seems to cause this error. Any updates?

**Comment by DominicTobias-b1** [comment]
I get it when trying to use something that has no arguments, is the syntax different in that case?

```js
export const NOTIFICATION_SUBSCRIPTION = gql`
  query NotificationSubscription() {
    datastore_notification_vw() {
      id
      market_id
      price
      side
      size
      status
      time
      trader_id
      type
    }
  }
`
```

**Comment by abhinpai** [comment]
Hello team here is my query 

` public static readonly UserProfile = gql`
  {
    query gitUser($username: String!)
    {
      github{
        user(username: $username)
        {
          login
          id
          company
          avatar_url
        }
      }
    }
  }`;`

 ```
 const { loading, error, data } = useQuery(GitHubQuery.UserProfile, {
    variables: { username: value },
  });
```


and i am getting the error **Syntax Error: Expected Name, found "$"**
Gone through the thread found no luck :(

**Comment by jtich** [comment]
If it's a query without any arguments, be sure to omit the empty `()` in typeDefs.
