### ISSUE TITLE
Building dynamic aliases for mutations

### ISSUE THREAD

**Issue by aiosifelis** [apollographql/graphql-tag#202]
Hi everyone. I 'm trying to build a mutation that will contain dynamic aliases.

My mutation string looks like this

```
mutation myAction( $ids: [String!]!, $money: String  ) {
  myAction(ids: $ids, money: $money) {
    message
  }
}
```
and I want to make it like this

```
mutation myAction( $ids: [String!]!, $money: String  ) {
  1: myAction(ids: ["1"], money: "$45") { message }
  2: myAction(ids: ["2"], money: "$200") { message }
  n: myAction(ids: ["n"], money: "$n") { message }
}
```

My code is trying to use the graphql-tag component by doing something like this
```
import gql from 'graphql-tag'

const MUTATION_TAG = (placeholder) => gql`
mutation myAction( $ids: [String!]!, $money: String  ) {
  ${placeholder}
}
`

const doMyAction = () => {
// i save into state the selected ids
 const selectedIds = this.state.selected
 let placeholder = ''
  selectedIds.forEach(id => {
    // variable money here can be found in the row
    placeholder += `${id}: myAction(ids: ["${id}"], money: "${money}") { message }`
  })
  const mutation = MUTATION_TAG(placeholder)

  apolloClient.mutate({
    mutation,
   variables: {}
  }).then( blah).catch (blah)
}

```
The above code throws a `gql is not defined` error.
Can anyone help me into how I will be able to build a mutation with a dynamic string. 
Thanks in advance

**Comment by jnwng** [comment]
generally speaking, i'd advise against dynamic queries: https://blog.apollographql.com/5-benefits-of-static-graphql-queries-b7fa90b0b69a, mostly for tooling reasons.

in any case, this is likely either:
1) an issue with the import
2) something up with the dynamically generated query string

i'd recommend an AST builder to guarantee the correctness of your GraphQL query: https://github.com/imranolas/graphql-ast-types

please re-open if you're still having issues!
