### ISSUE TITLE
Named queries and mutations with simple return types can not be parsed

### ISSUE THREAD

**Issue by flpvsk** [apollographql/graphql-tag#204]
I'm trying to write a query on the client side that accepts a parameter and returns a simple type [like here](https://stackoverflow.com/questions/44737043/not-returning-data-from-graphql-mutation), but gql can't parse it. Am I doing something wrong or is it a bug?

Reproduction in tests: https://github.com/flpvsk/graphql-tag/commit/4c94f971feacfe6cc22b24ab334028a4629cac02

Query example:

```js
gql`
  mutation name($param: String!) {
    something(param: $param): Boolean
}`
```

Error:

```
Syntax Error: Expected Name, found :
```

**Issue Labels**

- [x] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

**Comment by flpvsk** [comment]
Found the issue. The query should look like that:

```js
gql`
  mutation name($param: String!) {
    something(param: $param)
}`
```

Closing this one.

**Comment by RobertWHurst** [comment]
The above doesn't seem to work for me. Also, it's lacking the return type entirely, I can't see that working generally.

**Comment by flpvsk** [comment]
@RobertWHurst clients can not specify types of data in gql statements, we do that in server's statements. That was my misunderstanding. Clients can only specify fields to query. `Boolean` value doesn't have any fields, that's why the "return" part is missing from the statement.

To sum it up:
- If a mutation returns a primitive value like in the example above, we don't write anything in the return part;
- If a mutation returns an object, we can query its fields, **same way we do in client's queries**:

```js
gql`
  mutation name($param: !String) {
    something(param: $param) {
      field1
      field2
    }
}`
```
