### ISSUE TITLE
Add query type checking

### ISSUE THREAD

**Issue by aspirisen** [apollographql/graphql-tag#205]
Hello, I write queries in separate `.graphql` files and use `graphql-tag/loader` to load these files. I noticed that if I have a mistake in query this loader doesn't notify about it. Is it possible to make the loader to notify about errors in queries.
```
"apollo-boost": "0.1.14",
"apollo-server-express": "1.3.6",
"graphql": "14.0.0-rc.1",
"webpack": "3.12.0",
"ts-graphql-plugin": "1.1.2",
```

**Comment by jnwng** [comment]
@aspirisen this library doesn't do schema checking but you should check out [eslint-plugin-graphql](https://www.github.com/apollographql/eslint-plugin-graphql) or [graphql-schema-linter](https://github.com/cjoudrey/graphql-schema-linter) which are both better suited for this!
