### ISSUE TITLE
Add graphql 14.0.0 to peerDependencies

### ISSUE THREAD

**Issue by jonaskello** [apollographql/graphql-tag#208]
The graphql package is released in major version at 14.0.0 and if it would be nice it could be supported as peerDependency.

Please also see [this comment](https://github.com/apollographql/graphql-tools/issues/945#issuecomment-417663384).

**Comment by NaLLiFFuNT** [comment]
Is any updates here?

**Comment by jnwng** [comment]
just confirming that we need to do a major or minor bump before we send
this out. i don’t know enough about typescript to be able to figure that
out but want to make sure we’re not breaking setups unnecessarily.

**Comment by jnwng** [comment]
closed by #211, live in 2.10
