### ISSUE TITLE
How to add experimental fragment to webpack graphql-tag/loader?

### ISSUE THREAD

**Issue by raymondsze** [apollographql/graphql-tag#209]
As title.
Is it supported or not?

**Issue Labels**

- [ ] has-reproduction
- [ ] feature
- [ ] docs
- [ ] blocking
- [x] good first issue

**Comment by jnwng** [comment]
i assume you're talking about experimental fragment variables, if so, they're available now: https://github.com/apollographql/graphql-tag#experimental-fragment-variables

**Comment by marcelalburg** [comment]
I think, this question goes more in the direction, how can we enable this experimental feature if we're using the webpack graphql-tag/loader ?

```
config.module.rules.push({
            test: /\.(graphql|gql)$/,
            exclude: /node_modules/,
            use: [
                {
                    loader: 'graphql-tag/loader',
                },
            ],
        });
```

Is it possible to pass an option to this loader so that we can use this experimental feature with the webpack loader ?

Thanks
