### ISSUE TITLE
Can't find variable __makeTemplateObject

### ISSUE THREAD

**Issue by fhackenb** [apollographql/graphql-tag#216]
I'm attempting to use the graphql-tag library in an angular project and am getting an error:

> file:///app/graphql/queries/getAllPosts.js:4:101: JS ERROR ReferenceError: Can't find variable: __makeTemplateObject

My getAllPosts.ts file is:

`import gql from 'graphql-tag';

export default gql`
query GetAllPosts {
    getAllPosts {
      id
      title
      author
      ups
      content
    }
}`;
`

That's getting converted to js as:

`"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var graphql_tag_1 = require("graphql-tag");
exports.default = graphql_tag_1.default(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\nquery GetAllPosts {\n    getAllPosts {\n      id\n      title\n      author\n      ups\n      content\n    }\n}"], ["\nquery GetAllPosts {\n    getAllPosts {\n      id\n      title\n      author\n      ups\n      content\n    }\n}"])));
var templateObject_1;`

I've tried multiple versions of graphql-tag. My current version is 2.5.0, but I've also tried the @latest to the same effect. 

Any ideas?

**Comment by jnwng** [comment]
this looks like an issue in the compilation / transpilation process. take a look at what babel does out of the box here: https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAcwI4Bs4DMoRHA5AqAQzAAtUBaGQhXAbgCh6BTAD0ljgBMn1CBXFPGQoABkj5MoATzgBxJjACCKFAAUIAZxga4Ab0QLlazdr1xgnODGAwUTOPxglocPmB0BjCADsYTX3AAvkEiDEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

what are you using to compile your code?

**Comment by jnwng** [comment]
(closing this issue because it's not an issue with `graphql-tag` in particular). happy to continue the discussion to help debug
