### ISSUE TITLE
 graphql-tag@2.9.2 causes npm warning when used with graphql 14.0.2

### ISSUE THREAD

**Issue by mattes3** [apollographql/graphql-tag#217]
When I use version 2.9.2 together with graphql@14.0.2, I get an npm warning:

npm WARN graphql-tag@2.9.2 requires a peer of graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

Doesn't it run with V14 or do the dependencies need to be adjusted?

**Comment by bin16** [comment]
+1 for same question
