### ISSUE TITLE
Update CHANGELOG.md

### ISSUE THREAD

**Issue by darylf** [apollographql/graphql-tag#219]
It looks like there was a version bump to 2.10.0 two days ago, which seems to include support for `graphql@14`, but the change log wasn't updated. It would be helpful to know if there were any additional changes.

**Issue Labels**
- [x] docs

**Comment by lukewlms** [comment]
This issue is over a month old - possible to get an update on what's in 2.10?  Thank you!

**Comment by jnwng** [comment]
absolutely, will double check and make sure that was the only change.

**Comment by jnwng** [comment]
addressed by #223
