### ISSUE TITLE
Ability to merge AST schemas?

### ISSUE THREAD

**Issue by mgcrea** [apollographql/graphql-tag#220]
**Issue Labels**

- [ ] has-reproduction
- [x] feature
- [ ] docs
- [ ] blocking
- [ ] good first issue

I'm looking for a way to merge ASTs of graphql schemas:

I'm using webpack on the server side with the following rule:

```
      {
        test: /\.(graphql)$/,
        loader: 'graphql-tag/loader'
      }
```

I tried to do:

```js
import bookSchema from './book.graphql';
import authorSchema from './author.graphql';

export default mergeSchemas({
  schemas: [bookSchema, authorSchema]
});
```

But it does not work (expects actual executable schemas and not AST parsed code).

Is there a way to do it?

**Comment by jnwng** [comment]
`graphql-tag` is designed for GraphQL queries, not GraphQL SDL. if you're looking to do schema merging / imports in SDL, i'd look at something like [graphql-import](https://github.com/prisma/graphql-import)
