### ISSUE TITLE
Error parsing the document

### ISSUE THREAD

**Issue by eedfa** [apollographql/graphql-tag#226]
Hi. When I try to make the following query 
`const loadBoards = gql`
query($boardName:String,$boardId:String){
  boards(boardName:$boardName,boardId:$boardId){
    boardName id ratingAmount ratingScore
   }
}
`
`
I get the following error:
`Error: "Network error: Expecting a parsed GraphQL document. Perhaps you need to wrap the query string in a "gql" tag? http://docs.apollostack.com/apollo-client/core.html#gql"`
Do you have any clue where can be the problem?

**Comment by jnwng** [comment]
@eedfa will probably need to see where you're passing this to `apollo-client`. likely the variable you're passing is actually just undefined instead of having any content at all

please re-open if you're still having this issue!
