### ISSUE TITLE
[Question] Multiple querys with  React and mongoose

### ISSUE THREAD

**Issue by Sk8er22** [apollographql/graphql-tag#232]
Thanks for your work, I'm starting with React + Apollo + Mongo and I have the following Questiion:

I have a table where:
TABLE_1
ID    ID_A    ID_B

Another table where 
TABLE_2
ID_A OTHERS_rows

I defined my tables as 
```
type TABLE_1  {
	id : ID
	id_a: ID
        id_b: ID
}

type table_2{
	id: ID
	name: String!
}
```

Now my problem is when I getAll table_1 and after that I do a .map about each object in the array to find it in table 2...

There is anyway to solve it with a join without declaring one object inside the other table??

**Comment by jnwng** [comment]
i don't think this is the right repository for this issue — you might want to look for whatever library you're using to translate GraphQL to MongoDB queries. this library merely translates strings into GraphQL documents using `graphql-js`.
