### ISSUE TITLE
Conform to the other repository standards

### ISSUE THREAD

**Issue by JoviDeCroock** [apollographql/graphql-tag#236]
I saw that every repository is using npm (package-lock), while here yarn.lock is used.

Should we convert this after this pr: https://github.com/apollographql/graphql-tag/pull/235 gets merged. Since this will impose some new deps etc.

**Comment by jnwng** [comment]
let's add the `package-lock.json` first to resolve dependency issues first before we introduce a whole set of unknowns when we translate to TypeScript

**Comment by JoviDeCroock** [comment]
I'll PR this tonight
