### ISSUE TITLE
Just add `graphql-js` to package.json 

### ISSUE THREAD

**Issue by myuseringithub** [apollographql/graphql-tag#241]
If `graphql-js` is required why not add it inside the module's dependencies in `package.json` file. I'm sorry but it doesn't make sense. 
Why does the user need to install `graphql-js` separately and similarly other packages that are required ? Any reasoning behind it ? Thanks

___
### Versions:
        "apollo-cache-inmemory": "^1.4.2",
        "apollo-client": "^2.4.12",
        "apollo-link-http": "^1.5.11",
        "graphql": "^14.1.1",
        "graphql-tag": "^2.10.1",
        "node-fetch": "^2.3.0"

**Comment by jnwng** [comment]
see https://nodejs.org/en/blog/npm/peer-dependencies/ for more details about the benefits of peer dependencies — in short, this allows us to support a whole range of dependencies without _forcing_ the end-user to install a *specific* version. of course, it will warn if you have no version of `graphql-js` installed, too (or an invalid one)

**Comment by myuseringithub** [comment]
Thanks
