### ISSUE TITLE
(0 , _graphql.graphql)(...) is not a function

### ISSUE THREAD

**Issue by sun2rise** [apollographql/graphql-tag#243]
Hi,
i have this strange error in my project, never had it before when using graphql
![image](https://user-images.githubusercontent.com/3852307/53749964-de81ff00-3ea8-11e9-8385-55204fdb1efe.png)

You can see the error yourself here
[![Edit graphcool-debug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m462ml2pp?fontsize=14)

Am I missing something?

**Comment by jnwng** [comment]
thanks for putting in the codesandbox! 

i think you’re looking for the [graphql HOC from react-apollo](https://www.apollographql.com/docs/react/api/react-apollo.html#graphql), not the export from this library. 

hope that helps.

**Comment by sun2rise** [comment]
Thanks!

**Comment by sun2rise** [comment]
Oh yeah... sorry man, I'm so tired
:big-facepalm:
