### ISSUE TITLE
Support existing graphql.schema.json

### ISSUE THREAD

**Issue by Vadorequest** [apollographql/graphql-tag#248]
I have the following code

```js
const createOrganisation = ({ name, label }) => {
  return gql`
      createOrganisation({
          name: ${name}
          labelFR: ${label}
          labelEN: ${label}
      }){
          id
      }`;
};
```

I get the following error:
> Syntax Error GraphQL (11:7) Unexpected Name "createOrganisation"

It's because `gql` doesn't resolve my schema, and I don't see a way of providing it.

I'm using https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/ (WebStorm plugin) which read an existing graphQL endpoint to retrieves the typeDefs dynamically. The plugin support works well, but I don't see how to add support to my custom `gql` tags.

**Comment by jnwng** [comment]
simple mistake — the string that goes inside the `gql` template literal should itself be a valid GraphQL query:

(yours)
```graphql
  createOrganization({ name: ${name}, ... }) { 
    id 
  }
```

what it should look like:
```graphql
query {
  createOrganization({ name: ${name}, ... }) { 
    id 
  }
}
```

`graphql-tag` is just delegating to `graphql-js` to parse your document, anyway.

p.s., i also think you're going to have an issue with your arguments, as arguments in graphql [must always be named](https://graphql.org/learn/schema/#arguments). you will need to name the arguments like:
```graphql
query {
  createOrganization(args: { name: ${name}, ... }) { 
    id 
  }
}
```

hope that helps!

**Comment by Vadorequest** [comment]
Thank you, I understand better. I was trying to use gql for "subqueries", because I'm concatenating strings to build several queries in the same "query". So this approach doesn't work for me, too bad.
