### ISSUE TITLE
dynamic graphql mutation

### ISSUE THREAD

**Issue by EhsanSarshar** [apollographql/graphql-tag#280]
Hi I want to use @include(if: Boolean) directive in my graphql mutation
but it return "unexpected character @" error.

here is my mutation

```
const UPDATE_COMPANY = gql`
    mutation (
        $name: String!
    ){
        updateCompany(
            names:  @include (if: $name) {
                create: {
                    value: $name
                }
            }
        ) {
             id
       }
}
```

I think it just support directive for query not mutation

**Comment by jnwng** [comment]
i don't think what you wrote is valid GraphQL — see the `graphql` AST parser on [astexplorer.net](https://astexplorer.net/#/gist/43093fb711876a37ee68116c1d2b2977/5a59b3bc60a098bc8a9defdc535292d2a56b6471)

i dont think you can add directives on arguments like that, but you _can_ add directives on the fields themselves:
```graphql
mutation($name: String!) {
  updateCompany(names: { create: { value: $name }}) @include(if: $name) {
    id
  }
}
```
however, this may not be valid either as thee `if` argument is looking for `Boolean` type, not a `String`. let me know if that helps!
