### ISSUE TITLE
Nuxt link failing - Uncaught TypeError

### ISSUE THREAD

**Issue by jasonday** [apollographql/graphql-tag#297]
There appears to be an issue with my graphQL query, as the template renders but the `nuxt-link` fails. It just shows the `catrule.ruleid` text, but is not in a link format. 

Template:
```
<li v-for="catrule in cat_rulesetCollection">
    <nuxt-link :to="`/cat-rule/` + catrule.ruleid">{{ catrule.ruleid }}</nuxt-link>
</li>
```

Apollo:
```
import gql from 'graphql-tag'
export default {
    apollo: {
        cat_rulesetCollection: gql` {
            cat_rulesetCollection(populate:1) {
                ruleid
                }
            }`
        }
    }
```

Error:
```
Uncaught TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at VueComponent.observe (nuxt-link.client.js?4e55:62)
```

**Comment by Kamsou** [comment]
hey @jasonday  I have a same problem. Did you figure it out?

**Comment by jasonday** [comment]
> hey @jasonday I have a same problem. Did you figure it out?

So, I think the issue is related to having both apollo and axios installed simultaneously. I don't remember the exact specifics, but I think that's the basics. 

I ended up moving to 11ty, as using Nuxt for static site generation was too cumbersome.

**Comment by Kamsou** [comment]
ok its work now! thanks
