### ISSUE TITLE
graphql 15 compatibilty 

### ISSUE THREAD

**Issue by rchl** [apollographql/graphql-tag#298]
Is this package fully compatible with v15 of https://www.npmjs.com/package/graphql?
If yes then peerDependencies should be updated to include it.

**Comment by mehmetnyarar** [comment]
Looks like `"graphql-tag": "^2.10.3"` is not compatible with `"graphql": "15.1.0"`. It throws an error regarding `DocumentNode`:

> Argument of type 'import("./node_modules/graphql-tag/node_modules/graphql/language/ast").DocumentNode' is not assignable to parameter of type 'import("./node_modules/graphql/language/ast").DocumentNode'.
  Types of property 'loc' are incompatible

**Comment by adieuadieu** [comment]
Also ended up here as I was receiving an error `Must provide Source. Received: undefined`. Not sure if correlation or causation.

**Comment by Cito** [comment]
@mehmetnyarar This looks more like an incompatibility between two different versions of graphql.js (the one installed with graphql-tag and the one installed separately), not between graphql-tag and graphql.js. In the new version of graphql.js, the `loc` is an ES6 class.

**Comment by qortex** [comment]
Any update on this guys?
