### ISSUE TITLE
v2.12.0 and higher break support for IE11

### ISSUE THREAD

**Issue by tomdenbraber** [apollographql/graphql-tag#373]
We use the `apollo/client` package, which includes the graphql-tag-package. From apollo/client 3.3.9 and up, it requires graphql-tag 2.12.0 or higher. Unfortunately, graphql-tag 2.12.0 seems to break support for IE11. We would appreciate it very much if support for IE11 can be maintained.

**Intended outcome**
We'd like to keep using this package, with IE11 support.

**Actual outcome**
The package does not work when using v2.12.0 and higher, due to the newly introduced `Object.assign`-call here:
https://github.com/apollographql/graphql-tag/blob/dfe0e6220dd74b6952178739ef93a6a99a6875b4/src/index.ts#L153

`Object.assign` is [not supported](https://caniuse.com/mdn-javascript_builtins_object_assign) in IE11.

**How to reproduce the issue**
By creating a small application and building it with Webpack, we can observe that the output does indeed contain `Object.assign`.

Create an `index.js` file as follows:

```
import {gql} from "graphql-tag";
gql("foo");
```

and a `webpack.config.js`:

```
module.exports = {
	context: __dirname,
	entry: "./index",
	output: { filename: "bundle.js" },
	module: {}
}
```

Now, build the package and check the `bundle.js`-file. The code can be run in Chrome and other modern browsers, yet not in IE11.

Thanks in advance for looking at the issue :)!

**Comment by benjamn** [comment]
@tomdenbraber PR in progress: #380

**Comment by tomdenbraber** [comment]
@benjamn And merged already, thanks a lot!
