### ISSUE TITLE
Sourcemaps point to incorrect files

### ISSUE THREAD

**Issue by isuru88** [apollographql/graphql-tag#389]
After upgrading from  2.11.0 to 2.12.1, It seems like the packaged output does not contain `src` which is required by the source maps. 

When using @apollo/client v3.3.11, webpack throws the following warning, 
```
WARNING in C:/git/CustomizableSolution/node_modules/@apollo/client/node_modules/graphql-tag/lib/index.js
Module Warning (from C:/git/CustomizableSolution/node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/index.ts': Error: Can't resolve '../src/index.ts' in 'C:\git\CustomizableSolution\node_modules\@apollo\client\node_modules\graphql-tag\lib'
 @ C:/git/CustomizableSolution/node_modules/@apollo/client/core/index.js 15:0-30 16:25-28 17:30-33 18:42-45 19:43-46 20:0-15
 @ C:/git/CustomizableSolution/node_modules/@apollo/client/index.js
 @ ./src/apolloClient.ts
 @ ./src/index.tsx
 @ multi C:/git/CustomizableSolution/node_modules/piral-cli-webpack/lib/set-path ./src/index.tsx
```

**Steps to reproduce**: 
- Package using `npm pack`
- Extract and examine contents of `.map` type files within `lib`

**Expected output**: 
- Since the sources point to files within `src`. package should contain `src`

**Actual output**: 
- Package does not contain `src`

**Comment by tobyweslin** [comment]
I have the exact same issue.
