### ISSUE TITLE
[loader] Add "use strict" or document node 6 requirement

### ISSUE THREAD

**Issue by pward123** [apollographql/graphql-tag#39]
I get the following error when using the loader in webpack 2 with node 4.6.1:

```Module build failed: SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode```

This can be fixed by adding `"use strict";` to the top of loader.js or switching to node 6.  I'm not sure if you want to add strict mode or document the requirement.

**Comment by jnwng** [comment]
there's nothing in the webpack loader that would necessitate a hard dependency on node 6, so i would hesitate to suggest enforcing that.

there's a couple of solutions here:

1. compile down the loader code ala [babel-loader](https://github.com/babel/babel-loader/blob/master/package.json#L39) which would future-proof this particular module
2. just change the `let` statement to a `var` statement or add the `use strict;` directive you mentioned.

while i'd prefer that we do the former (compiling the loader), i'd be happy to accept a PR with the latter (adding `use strict;` or changing the `let` statement) in the meantime.

**Comment by jnwng** [comment]
linking with #32 as i suspect this will be something to address when the webpack loader is extracted

**Comment by jnwng** [comment]
addressed by #41. @pward123 unfortunately didn't see that you had created this in your fork, in the future you can send a [pull request](https://help.github.com/articles/about-pull-requests/) so that we can pull your code back into this repository.
