### ISSUE TITLE
Unexpected name "null" when null is provided to an arguments

### ISSUE THREAD

**Issue by alansmithribae** [apollographql/graphql-tag#47]
I have a use case where i'm trying to get root nodes of a tree represented in a relational database - i've used GraphQL to wrap around Sequelize.

To achieved this, I want to pass "null" as an argument to my GraphQL server as part of the query - according to the GraphQL spec null parameter values are allowed (http://facebook.github.io/graphql/#sec-Null-Value). However, graphql-tag seems to throw the following error when parsing the query:

Syntax Error GraphQL (2:25) Unexpected Name "null"
1: query {
2:         taxon(parentId: null) {
                           ^
3:           id,

I have a workaround for this issue - but just wondered whether it was intended functionality?

Thanks,

Alan

**Comment by okbel** [comment]
I'm facing the same issue too. Could you find a work arround for it? 😰  @alansmithribae

**Comment by jnwng** [comment]
@alansmithribae @okbel sorry for taking so long to address this issue - i dug deeper into this and found that passing `null` as a field argument was added in [graphql-js@v0.8.0](https://github.com/graphql/graphql-js/releases/tag/v0.8.0), specifically in [#544](https://github.com/graphql/graphql-js/pull/544). 

we updated `graphql-tag` with `graphql-js@v0.9.0` in [graphql-tag@1.2.4](https://github.com/apollographql/graphql-tag/commit/672e8d29ee751e4b4f74a39605cbc7af5d12c5b4) - could you double-check that you both have the latest version of `graphql-tag`?

**Comment by alansmithribae** [comment]
Thanks @jnwng for getting back to me. I double checked the version and I am using graphql-tag v1.2.4. I'm using it with angular 2 by the way - not sure if this makes a difference.
@okbel my workaround was very primitive - my database id's are positive numbers. In my query, I pass -1 instead of null. Server-side, I assume that parentId: -1 means 'select ... from ... where parentId is null'. But I am only prototyping, NOT writing production code!

**Comment by jnwng** [comment]
@alansmithribae ah, you're correct - we _used_ to bundle the `graphql` parser in the build process, so we're probably bundling an older version of `graphql` in 1.2.4. luckily, @abhiaiyer91 already addressed this by making sure we depend on the `graphql` package [here](https://github.com/apollographql/graphql-tag/pull/46), we just need to cut a new release. i'll prep the release and it'll probably be out in 1.3.0 (i'll loop back when its live)

**Comment by jnwng** [comment]
this should be resolved as part of `graphql-tag@v1.3.0`
