### ISSUE TITLE
v1.3 and v2.0

### ISSUE THREAD

**Issue by jnwng** [apollographql/graphql-tag#54]
wanted to write down what i'll be prepping in the next few days for posterity so people aren't waiting unnecessarily for their issues to get resolved.

there's a couple of issues with the upcoming minor / major versions of `graphql-tag`, in particular, we want to move `graphql-js` to be an external dependency and no longer bundled within `graphql-tag`. however, this is a fairly _major_ change since it will
1) introduce a new, potentially larger set of dependencies from `graphql`
2) removes two previously exported values from the `graphql` printer and parse (`print` and `parse`, respectively) that others may depend on (in particular, [apollo-client](https://github.com/apollographql/apollo-client), [react-apollo](https://github.com/apollographql/react-apollo/blob/e241140855a6e7977ee8953645cea70948545710/src/test-utils.tsx#L15), and [angular-apollo](https://github.com/apollographql/apollo-angular/blob/0ec93940411b50f9d24d3580e6a8c43993161cdb/tests/_mocks.ts#L4)

however, upgrading the bundled version of `graphql` within `graphql-tag` is important since it resolves issues that were resolved upstream like #47. we also want to make sure we're deprecating the fields we're removing from the `graphql-tag` module.

thus, here's what's coming in v1.3 and v2.0:

### v1.3
v1.3 will contain a **bundled** version of `graphql@^0.9.0`, as well as deprecation notices for both `print` and `parse`. 
- this will resolve #47 for those who want to stay with the bundled version of `graphql`

### v2.0
v2.0 will contain the changes currently in master to move from using the bundled version of `graphql` to establishing `graphql` as a peerDependency. we'll also remove the previously mentioned exports
- this will resolve #49

v1.3 is straightforward and will get done earlier rather than later, and v2.0 may take a little bit of testing to make sure it doesn't bloat our upstream clients (i'll start with a beta release of 2.0 and see how it interacts with apollo-client)

/cc @stubailo and @helfer 

EDIT: if you're using one of the deprecated exports, you should use `graphql/language/parser` and `graphql/language/printer` moving forward (`graphql-tag` will be using those too in v2.0)

**Comment by jnwng** [comment]
now that v1.3.0 is released,  we'll be doing a little bit of git reverting to make sure we can insert the v1.3.0 changes before the v2.0 changes that are currently on master.

**Comment by timbrandin** [comment]
I get these warnings all over now:
```
W20170301-11:17:42.782(1)? (STDERR) Warning - the `parser` exports from `graphql-tag` will be removed in the next major version.
W20170301-11:17:42.782(1)? (STDERR) See https://github.com/apollographql/graphql-tag/issues/54 for more information.
```

But I haven't imported anything else than this way:
```js
import gql from 'graphql-tag';
```

How do I resolve this?

**Comment by jnwng** [comment]
Ah - I added the deprecation warning for people importing the bundled
parser and printer, but guess what: we use it too. I'll release a patch to
silence those errors when 'graphql-tag' uses the bundled modules.

**Comment by jnwng** [comment]
@timbrandin v1.3.1 should resolve this for you - sorry about that!

**Comment by timbrandin** [comment]
Awesome! 👌

**Comment by timbrandin** [comment]
Btw, I still get the warning in the console on the client: 
```
Warning - the `printer` exports from `graphql-tag` will be removed in the next major version.
See https://github.com/apollographql/graphql-tag/issues/54 for more information.
```

**Comment by jamiter** [comment]
Had to lock our version to 1.2.x, because these logs crashed our PDF generation in production. Is there a way to ignore these warnings? Something like marking them as "seen".

Our bad for nog locking all npm dependencies though 😉

**Comment by jnwng** [comment]
@timbrandin apologies, forgot to make the proper adjustments in `apollo-client` to skip the deprecation warnings since we know we need to change those references when the next major version of `graphql-tag` comes through - see [apollo-client#1356](https://github.com/apollographql/apollo-client/issues/1356) for a patch fix to `apollo-client` to skip over the deprecation warnings.

@jamiter if you're using the `printer` or `parser` export from `graphql-tag`, you can safely use `graphql-tag/bundledPrinter` or `graphql-tag/bundledParser` (respectively) to "skip" the warnings.  do note that we *are* going to deprecate that export, so if you need to use `printer` or `parser`, you should use the equivalent export from `graphql/language/printer` or `graphql/language/parser`. if you're using one of the clients like `apollo-client`, see the above PR to skip over those warnings.

**Comment by helfer** [comment]
@jnwng In the future we should make sure that each warning is only printed once. My bad for not making sure this time.

**Comment by jnwng** [comment]
both v1.3 and v2.0 are live now.
