### ISSUE TITLE
split('/n') does not work on Windows

### ISSUE THREAD

**Issue by yurigenin** [apollographql/graphql-tag#61]
The loader fails to process fragments correctly on Windows because split('\n') does not work there. Modifying it to use split('\n\r') works, however. So, you need to determine the correct newline/carriagereturn characters in a platform independent way.

**Comment by jnwng** [comment]
@yurigenin ah, yes, that's correct — good catch!

happy to accept a PR to fix this (maybe with a test if its something we can capture in a test), and we can get this into 1.3.2 as well as 2.0

**Comment by jbaxleyiii** [comment]
@jnwng I'll take care of this this week!

**Comment by wajb** [comment]
Hi. This has broken cross platform support for us. Since graphql files can be written on one platform should not mean they can't be read from another.

The [specifications](https://facebook.github.io/graphql/#sec-Line-Terminators) state
> line terminators...have no significance to the semantic meaning of a GraphQL query document.

Therefore, I believe, a Windows platform ought to be able to load a file written in Linux etc.

Can we split by `/(\r?\n)+/` in the loader.js?

**Comment by jnwng** [comment]
This should have been available as part of v2.2.1:
https://github.com/apollographql/graphql-tag/commit/70e77d987b894df4370691a09030d7d9d209cd80

Is that not working?

**Comment by justindoherty** [comment]
Unfortunately not, the query documents were written to have `\n` as the line terminator then when we try and run it on a Windows machine the `os.EOL` returns `\r\n` so it doesn't end up splitting on anything.

**Comment by jnwng** [comment]
I see. Any chance you'd be willing to submit a PR? It should be fairly
similar to the previous solution (and perhaps a test or two).

**Comment by wajb** [comment]
I see you fixed it already but I've submitted a [PR with test coverage](https://github.com/apollographql/graphql-tag/pull/103). I have also submitted a contributor agreement by email. Thanks.
