### ISSUE TITLE
Can't load .graphql files with webpack loader : Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by nabiltntn** [apollographql/graphql-tag#62]
Hi,
I am having errors when using webpack loader to load .graphql files :
```
Uncaught TypeError: Cannot read property 'filter' of undefined
    at Object.parser (parser.js:12)
```

When debugging, i saw that for some calls to parser function,  `document` is just a base64 string representation and not a valid object.

```
var fragments = document.definitions.filter(function (x) { return x.kind === 'FragmentDefinition'; });
```

**Comment by jnwng** [comment]
@nabiltntn do you mind providing some sample `.graphql` files that its having trouble with?

**Comment by nabiltntn** [comment]
@jnwng so the problem was because i am using the `url` loader before the `graphql-tag/loader`.
The solution is to add `graphql|gql` pattern to the exclude array :
```js 
{
        exclude: [
          /\.html$/,
          /\.(js|jsx)$/,
          /\.(graphql|gql)$/, // add graphql extensions if using url loader
          /\.css$/,
          /\.json$/,
          /\.svg$/
        ],
        loader: 'url',
        query: {
          limit: 10000,
          name: 'static/media/[name].[hash:8].[ext]'
        }
 },
{
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader'
}
```
Maybe it's Webpack specific, but i think it would be useful to add a note in docs about this.
Thanks
