### ISSUE TITLE
V2 causes error in angular-cli

### ISSUE THREAD

**Issue by jvbianchi** [apollographql/graphql-tag#68]
After updating to version 2, I got this error in angular-cli:

```
hashingcrypto.js:74
  this._handle.update(data, encoding);
               ^

TypeError: Data must be a string or a buffer
```
If I rollback to version 1.3.2 it works fine.

**Comment by jnwng** [comment]
Just to confirm, you're using this with Apollo-angular?

**Comment by jvbianchi** [comment]
I'm using:

```
"apollo-angular": "0.12.0",
"apollo-client": "1.0.0-rc.7",
```

**Comment by jnwng** [comment]
Okay, thank you. I'm not super familiar with angular-cli, is there an easy
to reproduce set of steps (i.e, is there a test in Apollo-angular failing,
or can I just clone that and run angular-cli)?

**Comment by jvbianchi** [comment]
From what I searched, this kind of error happens when there's some kind of export with a missing file, webpack doesn't like it.

```typescript
export { Some } from './missing-file';
```

**Comment by jnwng** [comment]
Okay - two exports were removed from graphql-tag (print and parse) so I
wonder if it's due to that.

I also think that perhaps the webpack loader might be acting up, It might
not be getting exported properly. If either of those rings a bell...

Will take a closer look as soon as I get to a computer. Sorry about that!

**Comment by jvbianchi** [comment]
any news?

**Comment by jnwng** [comment]
The webpack loader export works as expected.. it would help me to have a
super minimal reproduction case as I'm not familiar with angular /
angular-cli

**Comment by jvbianchi** [comment]
The problem was with my project.

Please accept my apologies.
