### ISSUE TITLE
[Feature request] Allow converting from schema to query syntax

### ISSUE THREAD

**Issue by AlexandreBonaventure** [apollographql/graphql-tag#69]
Hi guys, 
I've been using `graphql-tag` in production for a few weeks and it's great ! With the webpack loader, it becomes very neat. Lately, I've found that I spent too much time rewriting(copy-pasting) stuff from GraphiQl in order to build my .graphql files.

So it would save me a lot of time if I could have a tool to automatically generate .graph files against a graphql schema in .json (introspection query). I search a lot, but it seems to me that for now, no such things exists.
Don't know if it fits the scope of this package, but it def be a nice addition to the toolbox. You guys have any idea if it exist yet ? or maybe some advice to help me build such a tool ?

Thanks.

**Comment by jnwng** [comment]
@AlexandreBonaventure thanks for using `graphql-tag`, im happy that you're finding it useful.

 as for your request, im don't fully understand what you're trying to accomplish — if you're automatically generating `.graphql` files, where is the query coming from? how do you choose which fields you want? or do you want something like an "export" button from graphiql?

**Comment by AlexandreBonaventure** [comment]
What will be helpful would be a way to generate fragments automagicly.
Let's say I have this schema:
![screen shot 2017-03-28 at 15 56 54](https://cloud.githubusercontent.com/assets/4596409/24424688/802b25ea-13cf-11e7-8d1b-98860b905d21.png)

it will generate an GraphsEdgeBaseQuery.graphql file, like this: (...ommited some fields)
```
fragment EdgeBase on GraphsEdgeBaseQuery {
  id
  source_id
  target_id
  position
  condition {
    config {
      max
      min
    }
    kind
  }
}
```

Then I will be able to quickly comment fields I don't want and easily use it in a query like this.
```
#import "./GraphsEdgeBaseQuery.graphql"
query getEdge($id: String!) {
  edge(id: $id) {
    ...EdgeBase
  }
}
```

In medium to big scale apps it will save hours of copy pasting.

**Comment by jnwng** [comment]
i see, makes sense to me. unfortunately that's out of the scope of this particular library (we're just parsing graphql documents), but this sort of functionality sounds like it might be useful to add to graphiql itself. check out https://github.com/OlegIlyenko/graphiql-workspace for an example of how you might add functionality to graphiql
