### ISSUE TITLE
Is it possible to import types inside graphql files?

### ISSUE THREAD

**Issue by servermeta** [apollographql/graphql-tag#75]
I was trying to find the best way to modularize my app by splitting my schema file.

I was thinking that the `#import` decorator from `graphql-tag/loader` was simply concatenating files, but it looks like it works with fragments only?

Or is there a way to import types inside .graphql files?

How could I make something like this work?

Author.graphql
```
type Author {
    id: Int! # the ! means that every author object _must_ have an id
    firstName: String
    lastName: String
    posts: [Post] # the list of Posts by this author
}
```

Schema.graphql
```
#import "./Author.graphql"

type Post {
    id: Int!
    title: String
    author: Author
    votes: Int
}
# the schema allows the following query:
type Query {
    posts: [Post]
    author(id: Int!): Author
}
# this schema allows the following mutation:
type Mutation {
    upvotePost (
        postId: Int!
    ): Post
}
```

at the moment it fails with error: 

```
mamluk@mamluk-X1:~/Projects/volcano/ServerQL$ node dist/bundle.js
/home/mamluk/Projects/volcano/ServerQL/dist/bundle.js:18651
      throw new Error('Type "' + typeName + '" not found in document.');
      ^

Error: Type "Author" not found in document.
    at typeDefNamed (/home/mamluk/Projects/volcano/ServerQL/dist/bundle.js:18651:13)
    at produceType (/home/mamluk/Projects/volcano/ServerQL/dist/bundle.js:18621:19)
    at produceOutputType (/home/mamluk/Projects/volcano/ServerQL/dist/bundle.js:18630:46)
    at /home/mamluk/Projects/volcano/ServerQL/dist/bundle.js:18703:15
    at /home/mamluk/Projects/volcano/ServerQL/dist/bundle.js:9237:31
    at Array.reduce (native)
    at keyValMap (/home/mamluk/Projects/volcano/ServerQL/dist/bundle.js:9236:15)
    at makeFieldDefMap (/home/mamluk/Projects/volcano/ServerQL/dist/bundle.js:18699:36)
    at fields (/home/mamluk/Projects/volcano/ServerQL/dist/bundle.js:18690:16)
    at resolveThunk (/home/mamluk/Projects/volcano/ServerQL/dist/bundle.js:280:40)

```

**Comment by jnwng** [comment]
@servermeta sorry for the late response! 

a couple of things to cover, first, its important to note that the `#import` syntax is **only** available through the webpack-loader - if these `.graphql` files are not going through webpack, the `#import` is just a normal comment.

if you're using the webpack loader, the loader does not distinguish between "fragments" and "types" (see [here](https://github.com/apollographql/graphql-tag/blob/master/loader.js#L32)) so it should work as expected.

**Comment by jnwng** [comment]
going through and clearing issues - if this is still an issue with the latest version of `graphql-tag` ([which includes some fixes for the Webpack loader](https://github.com/apollographql/graphql-tag/blob/master/CHANGELOG.md#v210)), please feel free to re-open!
