### ISSUE TITLE
Webpack loader fails to correctly load files.

### ISSUE THREAD

**Issue by servermeta** [apollographql/graphql-tag#76]
**Intended Outcome**: .graphql files should be loaded via graphql-tag/loader

**Actual Outcome**: there is a plethora of funny bugs and race conditions

**How to reproduce the issue:** Check this repo:

https://github.com/volcano-group/ServerQL/tree/koa

babel-node works, but webpack building doesn't.

The webpack loader fails to correctly load .graphql files. 

Check also this issue: https://github.com/apollographql/graphql-tools/issues/322

**Comment by jnwng** [comment]
@servermeta i cloned (and checked out) the repo / branch in question, and didn't find any issues with the graphql-tag/loader (although, i would make sure you dont have _both_ the babel-plugin-inline-import **and** the graphql-tag/loader set up, as i dont know how those two might conflict). i had to remove the babel-plugin-inline-import and adjust the `Schema.graphql` file to be a valid GraphQL document, though.

im going to close this, but if you can provide more specific clarification on the "funny bugs" and "race conditions", i'd be happy to investigate further!

**Comment by brennancheung** [comment]
I'm finding weird caching issues when modifying a `*.graphql` schema.  It won't pick up the change even when restarting the server completely.  It's usually when I remove the `!` at the end of a field to allow it to be nullable.  I keep getting the error message that the field can't be nullable so it seems to be using the old schema.

**Comment by LaurenceM10** [comment]
I'm having same issue!
