### ISSUE TITLE
Support Field Descriptors

### ISSUE THREAD

**Issue by jamiter** [apollographql/graphql-tag#81]
I received the following report concerning Field Descriptors: https://github.com/Swydo/meteor-graphql/issues/4

---
Consider the example:

`test.graphql`:

```graphql
#import './channel.graphql'
#import './user.graphql'

# test type description
type Query {
  # test field description
  channels: [Channel],
  # test field description
  user: User,
}
```

GraphiQL shows "No Description" for all types and fields. Do I need to do some sort of configuration to get the descriptions to show up?

---

I would have expected the descriptions to be there because the loader in this packages uses the graphql-js parser, which is aware of the comments as descriptors since this commit: https://github.com/graphql/graphql-js/commit/331dc77924908909e86284315bda12c22f316f54

It's possible to manually add this feature by using the [`getDescription`](https://github.com/graphql/graphql-js/commit/331dc77924908909e86284315bda12c22f316f54#diff-2691b670eb7e51187edc1f918c624a70R474) function and applying it when parsing the document before `stripLoc` is applied.

The question is, why is this necessary and not available by default?

I could make a PR showing a working version of this. Al that is needed is using the `getDescription` funciton:

```js
var parser = require('graphql/language/parser');
var buildASTSchema = require('graphql/utilities/buildASTSchema');

var parse = parser.parse;
var getDescription = buildASTSchema.getDescription;

// ...

function stripLoc(doc, removeLocAtThisLevel) {
  // ...

  if (!doc.description) {
    var description = getDescription(doc);

    if (description) {
      doc.description = description;
    }
  }

  // ...
}
```

Let me know if I'm overlooking something here.

**Comment by jnwng** [comment]
this is live as of #99 and `graphql-tag@v2.4.0`. thank you @jamiter!
