### ISSUE TITLE
Webpack loader style for React-native 

### ISSUE THREAD

**Issue by mmahalwy** [apollographql/graphql-tag#88]
Is it possible to include the `.graphql` files in react-native as the webpack loader provides?

**Comment by jnwng** [comment]
unfortunately, no. i might look at some of the solutions in https://github.com/apollographql/graphql-tag/issues/31 but in short we need to translate the `.graphql` files to javascript modules for use in react-native.

one option to get around this is to have a separate module that just exports a call to `gql` and your graphql document, which is enough to allow you to separate your queries. the "import" functionality will come through the regular javascript imports.
