### ISSUE TITLE
Problem with loader on webpack

### ISSUE THREAD

**Issue by matheusrocha89** [apollographql/graphql-tag#96]
Hi guys I am having some problems trying to use the `graphql-tag/loader` with webpack on my project, I configure it but when I try to import the `.graphql` file keeps giving and error. It seems like `babel-loader` is trying to load the file instead of the `graphql-tag/loader`. I know it's not a bug I just want to know if somebody can help me to find what I'm doing wrong.
My config:

``` 
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      },
      {
        test: /\.(graphql|gql)$/,
        exclude: /node_modules/,
        loader: 'graphql-tag/loader',
      },
```

Error:
```/Users/matheus/Developer/rtr-frontend/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /Users/matheus/Developer/rtr-frontend/src/graphql/UpdateUser.gql: Unexpected token, expected ; (1:9)
> 1 | mutation updateUser($userId: String! $user: UserInput) {
    |          ^
  2 |   updateUser(id: $userId, user: $user) {
  3 |     id
  4 |     email
    at Parser.pp$5.raise (/Users/matheus/Developer/rtr-frontend/node_modules/babylon/lib/index.js:4373:13)
```

**Comment by jnwng** [comment]
@matheusrocha89 as we determined on the apollo slack, this was a webpack issue, not a graphql-tag issue

**Comment by matheusrocha89** [comment]
Ok @jnwng

**Comment by twelve17** [comment]
@jnwng can you provide a link to the apollo slack chat?  I'm experiencing this issue and could use a little context.  Thanks!

**Comment by twelve17** [comment]
@jnwng I did some searching and I think [this is the thread on the apollo slack](https://apollographql.slack.com/archives/C11QBB84R/p1496785566375995) you are referring to?  I see this is a while back, but do you by chance have the react app you tested with?  It seems the cause was suspected, but hard to confirm since your app is not available as a control for comparison.

**Comment by mjvalade** [comment]
Can anyone give some context to what was referenced in the Apollo Slack for those of us not in that Slack group please?

**Comment by gdi2290** [comment]
if this is a webpack issue did anyone create a webpack issue for this?
